### ISSUE TITLE
Heli Taxi stucked in mid air

### ISSUE THREAD

**Issue by kbytesys** [DUWS-R-Team/DUWS-R#111]
When I took the heli taxi, after I've marked the lz in the map, the heli take off, black screen and then the heli remains stucked immoble in mid air.

It makes heli taxi totally useless. There are any way to fix or to force the heli to move?

**Comment by fritogotlayed** [comment]
@kbytesys Thanks for creating the issue! I've noticed this before in a different branch. I honestly didn't think it was in the main branch of the code. Currently we're not aware of a way to fix it, or of a workaround >.>. I know that sucks but I'd rather be honest than not :smile: 

If you'd like to take a crack at a fix feel free to pull request something. @bolbies and myself are learning SQF as we go so you can't be any worse than either of us :grin:

**Comment by kbytesys** [comment]
This bug is also in vanilla DUWS, I think the whole chop taxi is broken. ATM, I'm unable to take a look in the code. :(

**Comment by rahlskog** [comment]
I have also recently encountered this, it seems to happen when the helo takes small arms fire. Once the enemy is dealt with the helo will continue. Note that the helo itself does not do it, but i had friendlies come in and kill off the enemy.

**Comment by thoms999** [comment]
Hello, i am new to duws-r, love it, but the heli taxi bug is so sad :(.
I am sure there is Something to do around line 165 of helotaxi.sqf : 
`waitUntil {ClickedTaxiPos distance _helo < 200  or (vehicle _pilot == _pilot or !alive _pilot)}; // wait until the helo is near the lz`
or why not just pop the heli exactly on LZ and done.

but i have no idea how to edit the scenario and test it on my pc. I've read the developers guide but it seems complicated to me as i have no experience with github and arma script. Do you have a "Arma script guide for dummies" ? I've just tried download your sources and load it on eden editor but i didn't success.

**Comment by fritogotlayed** [comment]
@thoms999 I'm sorry but I don't really have any other resources. To be frank, working inside the ArmA toolset kinda gave me a bad taste in my mouth. When I started working on this project I really didn't know any ArmA scripting at all. I managed to get a little working just by poking around some.

If I recall correctly I managed to find this link (http://www.armaholic.com/page.php?id=20465) shortly before I became too busy at work to really work on learning ArmA scripting. My day job asked me to switch programming languages from C# to Python. That ended up consuming my learning time so I never really got through the information in that tutorial. I hope that helps. If you're interested in taking over main development on the mission I can work on transferring the "DUWS-R-Team" over to you and figuring out how to go about switching the steam stuff to your user.

**Comment by thoms999** [comment]
Thanks for your reply and your link, i will keep playing and learn arma Scripting. Will contact you later if i become able to create intersting thing for duws-r, but i'm too "noob" for the moment :) !

**Comment by thoms999** [comment]
I think I have found a quick fix :

The original problem is that the heli flee if it is under fire, and so then stay in mid air.
So as said on http://www.armaholic.com/forums.php?m=posts&q=21342 :
Add `_helogroup allowFleeing 0;`  (after initialisation of _helogroup in helotaxi.sqf) will prevent this behavior.
Also i will change the setWaypointCombatMode using GREEN (Hold fire - defend only)  instead of BLUE (never fire)

Tried on my pc, it seems to work, i will test it more.

(A better solution could be to find a new emergency LZ  near of the original LZ, if pilot detect "too many" ennemies in zone (= much more powered than blufor). seems complicated to me for the moment !)

Also i have changed land type to "GET IN" / "GET OUT" instead of LAND.
https://community.bistudio.com/wiki/land
