### ISSUE TITLE
I've added safe spawns and've safely tested them ;)  - the files are attached.

### ISSUE THREAD

**Issue by TuxuHolyland** [DUWS-R-Team/DUWS-R#156]
Hi,
regarding my previous post: "Manned APC Spawned inside Command building"
https://github.com/DUWS-R-Team/DUWS-R/issues/153

I've tried to fix that spawn issue in "request_vehicle.sqf" and "request_squad.sqf" into safe spawning by using BIS_fnc_findSafePos and by changing:

_spawnPos = getpos player;
_spawnPos = [(_spawnPos select 0)+30, _spawnPos select 1];

into this:
request_vehicle.sqf:

//_spawnPos = getpos player; Blocked by Tuxu
_spawnPos = [getpos hq_blu1, 100, 250, 20, 0, 20, 0] call BIS_fnc_findSafePos; //changed by tuxu
_spawnPos = [(_spawnPos select 0)+30, _spawnPos select 1];

"request_squad.sqf":

//_spawnPos = getpos hq_blu1; blocked by Tuxu
_spawnPos = [getpos hq_blu1, 80, 250, 20, 0, 20, 0] call BIS_fnc_findSafePos;
_spawnPos = [(_spawnPos select 0)+15, _spawnPos select 1];

I wasn't sure about upping those into the build so I won't mess up something for you, also - I was trying to adhere to your own style of coding to make your life easier with my intervention.
Also - I've commented to make it easier to find my edits.

I hope this helps,

Regards.

[dialog.zip](https://github.com/DUWS-R-Team/DUWS-R/files/1150290/dialog.zip)

**Comment by ultranoobian** [comment]
Very good. Looks like it will work. 

I'll test it and make a commit that is attributed to you so we know that you contributed once I get back to work.

**Comment by TuxuHolyland** [comment]
250 appears to be way far, ive changed the squad values to be 40..70 and the vehicle values to be 70..110

**Comment by ultranoobian** [comment]
Okay, some things we need to address
- We need to handle condition where the `bis_fnc_findSafePos` spawner is unable to find a safe position, else it will just eat up command points.
- B_T_VTOL_01_infantry_F (which is the largest vehicle) has a bounding sphere of ~48.5 units, so we can lower the vehicle threshold.

Even better would probably be to use `findEmptyPosition` since it just returns empty array instead of the map center, and we can actually pass the vehicle class to it as well.
